blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/DenisGithuku/Bottan/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=
    about: Suggest a new feature or enhancement.
  - name: Bug Report
    url: https://github.com/DenisGithuku/Botan/issues/new?assignees=&labels=bug&template=bug_report.md&title=
    about: Report a problem with the application.
