package com.githukudenis.designsystem.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005CBA)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD7E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3F)
val md_theme_light_secondary = Color(0xFF006B57)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF66FAD5)
val md_theme_light_onSecondaryContainer = Color(0xFF002019)
val md_theme_light_tertiary = Color(0xFF626200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE9E963)
val md_theme_light_onTertiaryContainer = Color(0xFF1D1D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF00201E)
val md_theme_light_surface = Color(0xFFF2FFFD)
val md_theme_light_onSurface = Color(0xFF00201E)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFB1FFF8)
val md_theme_light_inverseSurface = Color(0xFF003734)
val md_theme_light_inversePrimary = Color(0xFFABC7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF005CBA)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFABC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F65)
val md_theme_dark_primaryContainer = Color(0xFF00458E)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E3FF)
val md_theme_dark_secondary = Color(0xFF42DEBA)
val md_theme_dark_onSecondary = Color(0xFF00382C)
val md_theme_dark_secondaryContainer = Color(0xFF005141)
val md_theme_dark_onSecondaryContainer = Color(0xFF66FAD5)
val md_theme_dark_tertiary = Color(0xFFCDCC4A)
val md_theme_dark_onTertiary = Color(0xFF323200)
val md_theme_dark_tertiaryContainer = Color(0xFF4A4900)
val md_theme_dark_onTertiaryContainer = Color(0xFFE9E963)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201E)
val md_theme_dark_onBackground = Color(0xFF70F7EE)
val md_theme_dark_surface = Color(0xFF00201E)
val md_theme_dark_onSurface = Color(0xFF70F7EE)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF00201E)
val md_theme_dark_inverseSurface = Color(0xFF70F7EE)
val md_theme_dark_inversePrimary = Color(0xFF005CBA)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFABC7FF)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF0077ED)
